// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2f3e4ttAuRo_74Aw7gGjsid2-u8yruM',
    appId: '1:754744100437:web:5a9d35ed10677bb12c76dc',
    messagingSenderId: '754744100437',
    projectId: 'pcist-f93f7',
    authDomain: 'pcist-f93f7.firebaseapp.com',
    storageBucket: 'pcist-f93f7.firebasestorage.app',
    measurementId: 'G-E5TEMF5MX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23odDRfFHc3GDm4JM1qwlRVgEpEkppvQ',
    appId: '1:754744100437:android:64e609bf336bfdc72c76dc',
    messagingSenderId: '754744100437',
    projectId: 'pcist-f93f7',
    storageBucket: 'pcist-f93f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrbliWNc75Q847rLncg4Y0Sza5zkqWej0',
    appId: '1:754744100437:ios:2a8611fbbee3d0eb2c76dc',
    messagingSenderId: '754744100437',
    projectId: 'pcist-f93f7',
    storageBucket: 'pcist-f93f7.firebasestorage.app',
    iosBundleId: 'com.example.pcist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrbliWNc75Q847rLncg4Y0Sza5zkqWej0',
    appId: '1:754744100437:ios:2a8611fbbee3d0eb2c76dc',
    messagingSenderId: '754744100437',
    projectId: 'pcist-f93f7',
    storageBucket: 'pcist-f93f7.firebasestorage.app',
    iosBundleId: 'com.example.pcist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo2f3e4ttAuRo_74Aw7gGjsid2-u8yruM',
    appId: '1:754744100437:web:a85e48fc1f75afdd2c76dc',
    messagingSenderId: '754744100437',
    projectId: 'pcist-f93f7',
    authDomain: 'pcist-f93f7.firebaseapp.com',
    storageBucket: 'pcist-f93f7.firebasestorage.app',
    measurementId: 'G-QFXFDSCSCW',
  );
}
